name: 'Build ROS2'
on:
  push:
    branches: [ main ]

jobs:
  check:
    runs-on: macos-13

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Tectonic
        run: ./build.sh
